{% set name = "u-msgpack-python" %}
{% set version = "2.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 754edb07eaee39a9686a99823892e3a1be4e0948d9cc5c717946750c27643c9c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - umsgpack

about:
  home: https://github.com/vsergeev/u-msgpack-python
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A portable, lightweight MessagePack serializer and deserializer written in pure Python.
  dev_url: https://github.com/vsergeev/u-msgpack-python

extra:
  recipe-maintainers:
    - tschoonj
